// client/src/App.vue
<template>
  <div class="container">
    <img class="app-logo" src="./assets/logo.png" alt="SpaceX" />
    <router-view />
  </div>
</template>

<script lang="ts">
import {
  ApolloClient,
  createHttpLink,
  InMemoryCache,
} from '@apollo/client/core'
import { provideApolloClient } from '@vue/apollo-composable'

export default {
  setup(): void {
    const client = new ApolloClient({
      cache: new InMemoryCache(),
      link: createHttpLink({ uri: 'http://localhost:4000/query' }),
    })

    provideApolloClient(client)
  },
}
</script>

<style lang="scss">
.app-logo {
  display: block;
  width: 300;
  margin: auto;
}
</style>

// client/src/App.tsx
import React from 'react'
import { ApolloClient, ApolloProvider, InMemoryCache } from '@apollo/client'
import { BrowserRouter, Route } from 'react-router-dom'
import Launches from './components/Launches'
import Launch from './components/Launch'
import logo from './logo.png'

const client = new ApolloClient({
  uri: 'http://localhost:4000/query',
  cache: new InMemoryCache(),
})

const App = () => {
  return (
    <ApolloProvider client={client}>
      <BrowserRouter>
        <div className="container">
          <img src={logo} alt="SpaceX" style={{ width: 300, display: 'block', margin: 'auto' }} />
          <Route exact path="/" component={Launches} />
          <Route exact path="/launch/:flight_number" component={Launch} />
        </div>
      </BrowserRouter>
    </ApolloProvider>
  )
}

export default App
