// client/src/components/LaunchItem.vue
<template>
  <div class="card card-body mb-3">
    <div class="row">
      <div class="col-md-9">
        <h4>
          Mission:
          <span
            :class="{
              'text-success': launch_success,
              'text-danger': !launch_success,
            }"
            >{{ mission_name }}</span
          >
        </h4>
        <p>Date: {{ launchDate }}</p>
      </div>
      <div class="col-md-3">
        <router-link :to="{ path: `/launch/${flight_number}` }">
          Launch Details
        </router-link>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent } from 'vue'

export default defineComponent({
  props: {
    flight_number: {
      type: Number,
      default: 0,
    },
    mission_name: {
      type: String,
      default: '',
    },
    launch_date_local: {
      type: String,
      default: '',
    },
    launch_success: {
      type: Boolean,
      default: false,
    },
  },
  setup(props) {
    let launchDate = computed(() =>
      new Date(props.launch_date_local).toLocaleString(),
    )

    return {
      launchDate,
    }
  },
})
</script>

// client/src/components/LaunchItem.tsx
import React from 'react'
import Moment from 'react-moment'
import { Link } from 'react-router-dom'

interface Props {
  launch: {
    flight_number: number
    mission_name: string
    launch_date_local: string
    launch_success: string
  }
}

const LaunchItem = ({ launch: { flight_number, mission_name, launch_date_local, launch_success } }: Props) => {
  return (
    <div className="card card-body mb-3">
      <div className="row">
        <div className="col-md-9">
          <h4>
            Mission: <span className={launch_success ? 'text-success' : 'text-danger'}>{mission_name}</span>
          </h4>
          <p>
            Date: <Moment format="YYYY-MM-DD HH:mm">{launch_date_local}</Moment>
          </p>
        </div>
        <div className="col-md-3">
          <Link to={`/launch/${flight_number}`} className="btn btn-secondary">
            Launch Details
          </Link>
        </div>
      </div>
    </div>
  )
}

export default LaunchItem
