// client/src/views/Launch.vue
<template>
  <h4 v-if="loading">Loading...</h4>
  <h4 v-else-if="error">{{ error.message }}</h4>
  <template v-else>
    <h1 class="display-4 my-3">
      <span class="text-dark">Mission:</span>
      {{ result.launch.mission_name }}
    </h1>
    <h4 class="mb-3">Launch Details</h4>
    <ul class="list-group">
      <li class="list-group-item">
        Flight Number: {{ result.launch.flight_number }}
      </li>
      <li class="list-group-item">
        Launch Year: {{ result.launch.launch_year }}
      </li>
      <li class="list-group-item">
        Launch Successful:
        <span
          :class="{
            'text-success': result.launch.launch_success,
            'text-danger': !result.launch.launch_success,
          }"
          >{{ result.launch.launch_success ? 'Yes' : 'No' }}</span
        >
      </li>
    </ul>
    <h4 class="my-3">Rcoket Details</h4>
    <ul class="list-group">
      <li class="list-group-item">
        Rocket ID: {{ result.launch.rocket.rocket_id }}
      </li>
      <li class="list-group-item">
        Rocket Name: {{ result.launch.rocket.rocket_name }}
      </li>
      <li class="list-group-item">
        Rocket Type: {{ result.launch.rocket.rocket_type }}
      </li>
    </ul>
    <hr />
    <router-link class="btn btn-secondary" to="/">Back</router-link>
  </template>
</template>

<script lang="ts">
import { gql } from '@apollo/client/core'
import { useRoute } from 'vue-router'
import { useQuery } from '@vue/apollo-composable'

const launchQuery = gql`
  query($flight_number: Int!) {
    launch(flight_number: $flight_number) {
      flight_number
      mission_name
      launch_year
      launch_success
      launch_date_local
      rocket {
        rocket_id
        rocket_name
        rocket_type
      }
    }
  }
`

export default {
  setup() {
    const route = useRoute()
    const flight_number = parseInt(route.params.flight_number as string)
    const { loading, error, result } = useQuery(launchQuery, { flight_number })

    return {
      loading,
      error,
      result,
    }
  },
}
</script>

// client/src/components/Launch.tsx
import React from 'react'
import { gql, useQuery } from '@apollo/client'
import { Link, RouteComponentProps } from 'react-router-dom'

const launchQuery = gql`
  query($flight_number: Int!) {
    launch(flight_number: $flight_number) {
      flight_number
      mission_name
      launch_year
      launch_success
      launch_date_local
      rocket {
        rocket_id
        rocket_name
        rocket_type
      }
    }
  }
`

const Launch = (props: RouteComponentProps) => {
  let { flight_number }: any = props.match.params
  flight_number = parseInt(flight_number)

  const { loading, error, data } = useQuery(launchQuery, { variables: { flight_number } })

  if (loading) return <h4>Loading...</h4>
  if (error) console.log(error.message)

  return (
    <div>
      <h1 className="display-4 my-3">
        <span className="text-dark">Mission:</span>
        {data.launch.mission_name}
      </h1>
      <h4 className="mb-3">Launch Details</h4>
      <ul className="list-group">
        <li className="list-group-item">Flight Number: {data.launch.flight_number}</li>
        <li className="list-group-item">Launch Year: {data.launch.launch_year}</li>
        <li className="list-group-item">
          Launch Successful:
          <span className={data.launch.launch_success ? 'text-success' : 'text-danger'}>
            {data.launch.launch_success ? ' Yes' : ' No'}
          </span>
        </li>
      </ul>
      <h4 className="my-3">Rocket Details</h4>
      <ul className="list-group">
        <li className="list-group-item">Rocket ID: {data.launch.rocket.rocket_id}</li>
        <li className="list-group-item">Rocket Name: {data.launch.rocket.rocket_name}</li>
        <li className="list-group-item">Rocket Type: {data.launch.rocket.rocket_type}</li>
      </ul>
      <hr />
      <Link to="/" className="btn btn-secondary">
        Back
      </Link>
    </div>
  )
}

export default Launch
